name: Publish to mirror

# This workflow sync one-way from ggml-org/llama.cpp to ggerganov/llama.cpp
# Ref discussion: https://github.com/ggml-org/llama.cpp/pull/11887

on:
  push:
  workflow_dispatch: # allows manual triggering
  #schedule:
    # Re-run every 15 minutes
    #- cron: '*/15 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

# Fine-grant permission
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to mirror

    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync image
        shell: bash
        run: |
          set -e
          python sync.py
        env:
          PUSH_USERNAME: ${{ github.repository_owner }}
          PUSH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
